# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:

headerpic: "/img/logo.jpg"
# 导航栏上的顶部logo


# http://7ktu2f.com1.z0.glb.clouddn.com/IMG_20141031_193748.jpg

widgets:
- category
- archive

# 显示左侧需要展示的目录，建议使用三到五个目录 ，如果不设置的话当然也没有问题
category: 
- 前端
- 大学
- 生活



friendsCall: 那些小伙伴们 

friends:
- 百度火狐吧: http://tieba.baidu.com/f?kw=firefox
- 破袜子: http://pewae.com/
- 方室网志: http://fangshi.org/
- 张鑫旭-鑫空间: http://www.zhangxinxu.com/wordpress/
- Joyful Physics博客: http://www.cnblogs.com/joyfulphysics


slogan: "我们在自己的世界里独自狂欢"
#"分享是一种快乐"
#"我们在自己的世界里独自狂欢"

favicon: "/favicon.png"

# 右侧分享栏目里面的必要信息

twitter: 'zhangolve'
github: 'zhangolve'
weixin: 'http://7ktu2f.com1.z0.glb.clouddn.com/wechatopen.jpg'
email: 'zhangolve@gmail.com'


disqus: hktkdy-1

# disqus ID ，如果不设置的话，则为无评论状态

google_analytics: 'UA-51305251-1'
date: 'relative'
#在文章的展示页是否显示相对日期




copyright: true 

# 是否开启版权说明，true则默认在每篇文章的最后添加版权声明，如果想指定某一篇文章的版权，可以在文章结尾处添加---nocopyriht


reward: true
alipay: /img/alipay.jpg

# 如果已经开启了打赏功能，则在alipay的设置中添加你的图片位置或云图片链接。




iewarn: true 

# ie10-的不兼容性提示

# 标明博客的起始时间，对我们这种已经几年的博客，还是很有必要的。


since: 2014
