# Header
menu:
  Home: /
Archives: /archives
rss: /atom.xml
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:

headerpic: "/img/logo.jpg"

# 导航栏上的顶部logo 请自行替换需要显示的logo图片

# theme-color 配置此选项后，使用安卓Chrome系浏览器浏览本站时，将使状态栏主题颜色发生改变


theme_color: true


widgets:
- category
- archive

# 显示左侧需要展示的目录，建议使用三到五个目录 ，如果不设置的话当然也没有问题

category: 
- 前端
- 大学
- 生活


# 右侧边栏的友情链接名称 

friendsCall: 那些小伙伴们 

# 建议填入几个friens，否则主题会很丑。

friends:
  - 奥巴马的博客: http://localhost:4000/
  - 卡卡的美丽传说: http://localhost:4000/
  - 本泽马的博客: http://localhost:4000/
  - 吉格斯的博客: http://localhost:4000/
  - 习大大大不同: http://localhost:4000/
  - 托蒂的博客: http://localhost:4000/




# 右侧边栏网站slogan自定义

slogan: "我们在自己的世界里独自狂欢"

# 网站favicon 自定义
favicon: "/favicon.png"

# 右侧分享栏目里面的必要信息

twitter: 'zhangolve'
github: 'zhangolve'
weixin: 'http://7ktu2f.com1.z0.glb.clouddn.com/wechatopen.jpg'
email: 'zhangolve@gmail.com'

# disqus ID，不要搞错了。
# disqus ID ，如果不设置的话，则为无评论状态
# 如果不需要使用disqus，请也尽量不要删除这个字段。留空即可

disqus: 

# 网易云跟贴，填如你正确的productKey 
# 具体的配置方法 http://tie.163.com/gt/17/0119/16/CB5J9J3U00308CQ5.html#from=relevant#xwwzy_35_bottomnewskwd

# 如果不需要网易云跟贴，请留空该字段

cloudtie: "d9ac97642b446f585903fd" 


# 在引号内填入你的谷歌分析id。
google_analytics: ''

#在文章的展示页是否显示相对日期
date: 'relative'




# 是否开启版权说明，true则默认在每篇文章的最后添加版权声明，如果想指定某一篇文章的版权，
#可以在文章结尾处添加---nocopyriht ，详见实例文章sample.md
copyright: true 


# 如果已经开启了打赏功能，则在alipay的设置中添加你的图片位置或云图片链接。
reward: true
alipay: /img/alipay.jpg


# ie10-的不兼容性提示

iewarn: true 


# 标明博客的起始时间，对我们这种已经几年的博客，还是很有必要的。


since: 2014
