# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true


# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
friends:
- 百度火狐吧: http://tieba.baidu.com/f?kw=firefox
- 破袜子: http://pewae.com/
- 方室网志: http://fangshi.org/
- 张鑫旭-鑫空间: http://www.zhangxinxu.com/wordpress/
- Joyful Physics博客: http://www.cnblogs.com/joyfulphysics



# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter: 'zhangolve'
github: 'zhangolve'
weixin: 'http://7ktu2f.com1.z0.glb.clouddn.com/wechatopen.jpg'
fb_app_id:
