# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:

# Content
excerpt_link: Read More
fancybox: true

headerpic: "http://7ktu2f.com1.z0.glb.clouddn.com/IMG_20141031_193748.jpg"
# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
friends:
- 百度火狐吧: http://tieba.baidu.com/f?kw=firefox
- 破袜子: http://pewae.com/
- 方室网志: http://fangshi.org/
- 张鑫旭-鑫空间: http://www.zhangxinxu.com/wordpress/
- Joyful Physics博客: http://www.cnblogs.com/joyfulphysics



# widget behavior
archive_type: 'monthly'
show_count: false

slogan: "我们在自己的世界里独自狂欢"
#"分享是一种快乐"
#"我们在自己的世界里独自狂欢"

favicon: /favicon.png
twitter: 'zhangolve'
github: 'zhangolve'
weixin: 'http://7ktu2f.com1.z0.glb.clouddn.com/wechatopen.jpg'

duoshuo: hktkdy
google_analytics: 'UA-51305251-1'
date: 'relative'
reward: false
alipay: /img/alipay.jpg

selectionEffect: true

category: 
- 前端
- 大学
- 生活